// AUTH
export const SET_USERNAME = "SET_USERNAME";

export const FETCH_USER_BEGIN = "FETCH_USER_BEGIN";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAIL = "FETCH_USER_FAIL";

export const LOGIN_BEGIN = "LOGIN_BEGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOGIN_GUEST_SUCCESS = "LOGIN_GUEST_SUCCESS";
export const LOGIN_GUEST_FAIL = "LOGIN_GUEST_FAIL";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGOUT = "LOGOUT";

// PROJECTS
// Projects
export const SET_SELECTED_PROJECT = "SET_SELECTED_PROJECT";

export const FETCH_PROJECTS_BEGIN = "FETCH_PROJECTS_BEGIN";
export const FETCH_PROJECTS_SUCCESS = "FETCH_PROJECTS_SUCCESS";
export const FETCH_PROJECTS_FAIL = "FETCH_PROJECTS_FAIL";

export const CREATE_PROJECT_CLIENT = "CREATE_PROJECT_CLIENT";
export const CREATE_PROJECT_BEGIN = "CREATE_PROJECT_BEGIN";
export const CREATE_PROJECT_SUCCESS = "CREATE_PROJECT_SUCCESS";
export const CREATE_PROJECT_FAIL = "CREATE_PROJECT_FAIL";

export const RENAME_PROJECT_CLIENT = "RENAME_PROJECT_CLIENT";
export const RENAME_PROJECT_BEGIN = "RENAME_PROJECT_BEGIN";
export const RENAME_PROJECT_SUCCESS = "RENAME_PROJECT_SUCCESS";
export const RENAME_PROJECT_FAIL = "RENAME_PROJECT_FAIL";

export const DELETE_PROJECT_CLIENT = "DELETE_PROJECT_CLIENT";
export const DELETE_PROJECT_BEGIN = "DELETE_PROJECT_BEGIN";
export const DELETE_PROJECT_SUCCESS = "DELETE_PROJECT_SUCCESS";
export const DELETE_PROJECT_FAIL = "DELETE_PROJECT_FAIL";

// Channels
export const SET_SELECTED_CHANNEL = "SET_SELECTED_CHANNEL";

export const CREATE_CHANNEL_CLIENT = "CREATE_CHANNEL_CLIENT";
export const CREATE_CHANNEL_BEGIN = "CREATE_CHANNEL_BEGIN";
export const CREATE_CHANNEL_SUCCESS = "CREATE_CHANNEL_SUCCESS";
export const CREATE_CHANNEL_FAIL = "CREATE_CHANNEL_FAIL";

export const RENAME_CHANNEL_CLIENT = "RENAME_CHANNEL_CLIENT";
export const RENAME_CHANNEL_BEGIN = "RENAME_CHANNEL_BEGIN";
export const RENAME_CHANNEL_SUCCESS = "RENAME_CHANNEL_SUCCESS";
export const RENAME_CHANNEL_FAIL = "RENAME_CHANNEL_FAIL";

export const DELETE_CHANNEL_CLIENT = "DELETE_CHANNEL_CLIENT";
export const DELETE_CHANNEL_BEGIN = "DELETE_CHANNEL_BEGIN";
export const DELETE_CHANNEL_SUCCESS = "DELETE_CHANNEL_SUCCESS";
export const DELETE_CHANNEL_FAIL = "DELETE_CHANNEL_FAIL";

// Messages
export const CREATE_MESSAGE_CLIENT = "CREATE_MESSAGE_CLIENT";
export const CREATE_MESSAGE_BEGIN = "CREATE_MESSAGE_BEGIN";
export const CREATE_MESSAGE_SUCCESS = "CREATE_MESSAGE_SUCCESS";
export const CREATE_MESSAGE_FAIL = "CREATE_MESSAGE_FAIL";

export const DELETE_MESSAGE_CLIENT = "DELETE_MESSAGE_CLIENT";
export const DELETE_MESSAGE_BEGIN = "DELETE_MESSAGE_BEGIN";
export const DELETE_MESSAGE_SUCCESS = "DELETE_MESSAGE_SUCCESS";
export const DELETE_MESSAGE_FAIL = "DELETE_MESSAGE_FAIL";

// MODAL
export const CHANNEL_MODAL_OPEN = "CHANNEL_MODAL_OPEN";
export const CHANNEL_MODAL_CLOSE = "CHANNEL_MODAL_CLOSE";

export const PROJECT_MODAL_OPEN = "PROJECT_MODAL_OPEN";
export const PROJECT_MODAL_CLOSE = "PROJECT_MODAL_CLOSE";

export const FRIEND_MODAL_OPEN = "FRIEND_MODAL_OPEN";
export const FRIEND_MODAL_CLOSE = "FRIEND_MODAL_CLOSE";

export const INFO_MODAL_OPEN = "INFO_MODAL_OPEN";
export const INFO_MODAL_CLOSE = "INFO_MODAL_CLOSE";

// SOCKET
export const SET_SOCKET = "SET_SOCKET";

// HOME
export const SET_HOME_ITEM = "SET_HOME_ITEM";

// FRIENDS
export const SET_FRIEND_STATUS_DISPLAY = "SET_FRIEND_STATUS_DISPLAY";
export const STORE_FRIENDS = "STORE_FRIENDS";

export const SEND_FRIEND_REQUEST_CLIENT = "SEND_FRIEND_REQUEST_CLIENT";
export const SEND_FRIEND_REQUEST_BEGIN = "SEND_FRIEND_REQUEST_BEGIN";
export const SEND_FRIEND_REQUEST_SUCCESS = "SEND_FRIEND_REQUEST_SUCCESS";
export const SEND_FRIEND_REQUEST_FAIL = "SEND_FRIEND_REQUEST_FAIL";

export const DELETE_FRIEND_REQUEST_CLIENT = "DELETE_FRIEND_REQUEST_CLIENT";
export const DELETE_FRIEND_REQUEST_BEGIN = "DELETE_FRIEND_REQUEST_BEGIN";
export const DELETE_FRIEND_REQUEST_SUCCESS = "DELETE_FRIEND_REQUEST_SUCCESS";
export const DELETE_FRIEND_REQUEST_FAIL = "DELETE_FRIEND_REQUEST_FAIL";

export const ADD_FRIEND_CLIENT = "ADD_FRIEND_CLIENT";
export const ADD_FRIEND_BEGIN = "ADD_FRIEND_BEGIN";
export const ADD_FRIEND_SUCCESS = "ADD_FRIEND_SUCCESS";
export const ADD_FRIEND_FAIL = "ADD_FRIEND_FAIL";

export const DELETE_FRIEND_CLIENT = "DELETE_FRIEND_CLIENT";
export const DELETE_FRIEND_BEGIN = "DELETE_FRIEND_BEGIN";
export const DELETE_FRIEND_SUCCESS = "DELETE_FRIEND_SUCCESS";
export const DELETE_FRIEND_FAIL = "DELETE_FRIEND_FAIL";

// DIRECT MESSAGE
export const FETCH_DIRECT_MESSAGES_SUCCESS = "FETCH_DIRECT_MESSAGES_SUCCESS";
export const FETCH_DIRECT_MESSAGES_FAIL = "FETCH_DIRECT_MESSAGES_FAIL";

export const CREATE_DIRECT_MESSAGE_GROUP_CLIENT =
  "CREATE_DIRECT_MESSAGE_GROUP_CLIENT";
export const CREATE_DIRECT_MESSAGE_GROUP_SUCCESS =
  "CREATE_DIRECT_MESSAGE_GROUP_SUCCESS";
export const CREATE_DIRECT_MESSAGE_GROUP_FAIL =
  "CREATE_DIRECT_MESSAGE_GROUP_FAIL";

export const DELETE_DIRECT_MESSAGE_GROUP_CLIENT =
  "DELETE_DIRECT_MESSAGE_GROUP_CLIENT";
export const DELETE_DIRECT_MESSAGE_GROUP_SUCCESS =
  "DELETE_DIRECT_MESSAGE_GROUP_SUCCESS";
export const DELETE_DIRECT_MESSAGE_GROUP_FAIL =
  "DELETE_DIRECT_MESSAGE_GROUP_FAIL";

export const CREATE_DIRECT_MESSAGE_CLIENT = "CREATE_DIRECT_MESSAGE_CLIENT";
export const CREATE_DIRECT_MESSAGE_BEGIN = "CREATE_DIRECT_MESSAGE_BEGIN";
export const CREATE_DIRECT_MESSAGE_SUCCESS = "CREATE_DIRECT_MESSAGE_SUCCESS";
export const CREATE_DIRECT_MESSAGE_FAIL = "CREATE_DIRECT_MESSAGE_FAIL";

export const DELETE_DIRECT_MESSAGE_CLIENT = "DELETE_DIRECT_MESSAGE_CLIENT";
export const DELETE_DIRECT_MESSAGE_SUCCESS = "DELETE_DIRECT_MESSAGE_SUCCESS";
export const DELETE_DIRECT_MESSAGE_FAIL = "DELETE_DIRECT_MESSAGE_FAIL";
